name: Daily Commit

on:
  schedule:
    - cron: '0 7 * * *'   # 7 AM UTC
    - cron: '0 17 * * *'  # 5 PM UTC
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Make a daily change
        run: echo "Ping at: $(date -u)" >> activity.log

      - name: Configure Git
        run: |
          git config user.name "alfredbis29"
          git config user.email "kalumunabisimwa5@gmail.com"

      - name: Commit changes
        run: |
          git add activity.log
          git commit -m "📅 Auto ping at $(date -u)" || echo "No changes to commit"

      - name: Push changes securely
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/Alfredbis29/daily-commit-bott.git
          git push origin HEAD
